apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - dead-cell-svc.dead-cell.svc.cluster.local
  http:
    - fault:
        delay:
          fixedDelay: 1s
          percentage:
            value: 5
        abort:
          httpStatus: 503
          percentage:
            value: 10
      route:
        - destination:
            host: dead-cell-svc.dead-cell.svc.cluster.local
      retries:
        attempts: 3
        perTryTimeout: 2s
      timeout: 0.2s
