# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  create-cluster:
    desc: "Creates a Kind cluster from config file"
    cmd: kind create cluster --config infra/k8s/cluster.yml --name {{.CLI_ARGS}}
  delete-cluster:
    desc: "Delete Kind cluster"
    cmd: kind delete cluster --name {{.CLI_ARGS}}
  run-cell:
    desc: "Runs a cell locally"
    cmd: cd services/cell_{{.CLI_ARGS}} && go run cmd/api/main.go
