# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

env:
  CLUSTER_NAME: zygarde

tasks:
  create-cluster:
    desc: "Creates a Kind cluster from config file"
    cmd: kind create cluster --config k8s/cluster.yaml --name {{.CLUSTER_NAME}}
  delete-cluster:
    desc: "Delete Kind cluster"
    cmd: kind delete cluster --name {{.CLUSTER_NAME}}
  apply:
    desc: "Apply kustomize root"
    cmd: kubectl apply -k k8s/
  install-istio:
    desc: "Installs Istio to the current cluster"
    cmd: istioctl install -y
  install-k8s-gateway-crds:
    desc: "Installs Kubernetes Gateway CRDs"
    cmd: kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.6.0" | kubectl apply -f -
  scaffold:
    desc: "Scaffolds cluster, applying all needed infrastructure and manifests"
    cmds:
      - task: create-cluster
      - task: install-k8s-gateway-crds
      - task: install-istio
      - task: apply
