# yaml-language-server: $schema=none
namespace: dead-cell
namePrefix: dead-cell-
labels:
  - pairs:
      app.kubernetes.io/instance: dead-cell
      app.kubernetes.io/version: V1
    includeSelectors: true

resources:
  - ../../base

configMapGenerator:
  - name: config
    literals:
      - PORT=4000
      - CELL_ID=dead
      - IS_AVAILABLE=true
