# yaml-language-server: $schema=none
namespace: cell-a
namePrefix: cell-a-v2-
labels:
  - pairs:
      app.kubernetes.io/instance: cell-a
      app.kubernetes.io/version: V2
    includeSelectors: true

resources:
  - ../../base

configMapGenerator:
  - name: config
    literals:
      - PORT=4000
      - CELL_ID=a2
      - IS_AVAILABLE=true
