# yaml-language-server: $schema=none
namespace: cell-c
namePrefix: cell-c-
labels:
  - pairs:
      app.kubernetes.io/instance: cell-c
      app.kubernetes.io/version: V1
    includeSelectors: true

resources:
  - ../../base

configMapGenerator:
  - name: config
    literals:
      - PORT=4000
      - CELL_ID=c
      - IS_AVAILABLE=true
