# yaml-language-server: $schema=none
apiVersion: v1
kind: Namespace
metadata:
  name: cell-a
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    istio.io/use-waypoint-namespace: default
