apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: dr
spec:
  host: dead-cell-svc.dead-cell.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      consecutiveGatewayErrors: 3
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
